# Generated by Django 2.1.7 on 2019-02-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='设施名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('address', models.CharField(max_length=512, verbose_name='地址')),
                ('room_count', models.IntegerField(default=1, verbose_name='房间数量')),
                ('acreage', models.IntegerField(default=0, verbose_name='房屋面积')),
                ('unit', models.CharField(default='', max_length=32, verbose_name='房屋单元')),
                ('capacity', models.IntegerField(default=1, verbose_name='房屋容纳人数')),
                ('beds', models.CharField(default='', max_length=64, verbose_name='床铺配置')),
                ('deposit', models.IntegerField(default=0, verbose_name='房屋押金')),
                ('min_days', models.IntegerField(default=1, verbose_name='最少入住天数')),
                ('max_days', models.IntegerField(default=0, verbose_name='最多入住天数')),
                ('order_count', models.IntegerField(default=0, verbose_name='完成订单数')),
                ('index_image_url', models.CharField(max_length=256, verbose_name='房屋主图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.Facility', verbose_name='房屋设施')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.House')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('begin_data', models.DateField(verbose_name='预定的开始时间')),
                ('end_date', models.DateField(verbose_name='预定的结束时间')),
                ('days', models.IntegerField(default=1, verbose_name='预定的总天数')),
                ('house_price', models.IntegerField(verbose_name='房屋单价')),
                ('amount', models.IntegerField(verbose_name='订单总金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待接单'), (1, '待支付'), (2, '已支付'), (3, '待评价'), (4, '已完成'), (5, '已取消'), (6, '已拒单')], verbose_name='订单状态')),
                ('comment', models.TextField(max_length=128, verbose_name='拒单原因')),
                ('trade_no', models.CharField(max_length=128, verbose_name='交易编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.House')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=11)),
                ('real_name', models.CharField(max_length=32)),
                ('id_card', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.User'),
        ),
        migrations.AddField(
            model_name='house',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.User', verbose_name='房屋主人'),
        ),
        migrations.AddField(
            model_name='area',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihomeapp.House'),
        ),
    ]
