# Generated by Django 2.1.7 on 2019-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihomeapp', '0003_auto_20190228_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='house',
        ),
    ]
